name: gachiganjik_app
description: "[같이간직 앱] 함께 만드는 사진첩 서비스 - \"시간이 흘러도 빛날 이 순간들을 함께 보관하세요\""
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0  # 개발용 로그
  connectivity_plus: ^6.1.1

  # Local Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2

  # Firebase
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.6

  # Local DB (오프라인)
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  path_provider: ^2.1.5

  # Image
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.3.0
  gal: ^2.3.0
  permission_handler: ^11.3.1
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1

  # UI
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  shimmer: ^3.0.0

  # Utils
  intl: ^0.18.1
  mobile_scanner: ^7.0.0
  qr_flutter: ^4.1.0
  uuid: ^4.5.1

dev_dependencies:
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  #Isar Code Generation
  isar_community_generator: ^3.3.0
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

  # Android 13 이상 (Adaptive Icon)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
     - assets/images/logo2.png
     - assets/images/logo.png
     - assets/icons/album_icon.png
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
